<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailIndicateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailIndicateurRepository extends EntityRepository
{
    public function findByIndicateur($id){
        $qb = $this->createQueryBuilder('d')
            ->leftJoin('d.indicateur','indicateur')
            ->where('d.indicateur=:id')
            ->setParameter('id',$id)
            ->orderBy('d.dateDetail','DESC');
        return $qb->getQuery()->getResult();
    }

    public function findByUnite($id){
        $qb = $this->createQueryBuilder('d')
            ->leftJoin('d.unite','unite')
            ->where('d.unite=:id')
            ->setParameter('id',$id)
            ->orderBy('d.dateDetail','DESC');
        return $qb->getQuery()->getResult();
    }

    public function findByUniteAndIndicateur($uniteId,$indicateurId){
        $qb = $this->createQueryBuilder('d')
            ->leftJoin('d.indicateur','indicateur')
            ->leftJoin('d.unite','unite')
            ->where('d.indicateur=:indicateurId')
            ->andWhere('d.unite=:uniteId')
            ->setParameter('indicateurId',$indicateurId)
            ->setParameter('uniteId',$uniteId)
            ->orderBy('d.dateDetail','DESC');
        return $qb->getQuery()->getResult();

    }

}
