<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IndicateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicateurRepository extends EntityRepository
{
    public function all(){
        $q = $this->createQueryBuilder('i')
            ->leftJoin('i.hotes','hoste');
        return $q->getQuery()->getResult();
    }
}
